### PR TITLE
Extra hauler for every 2k backlog in mining containers

### PR DESCRIPTION
**Pull request by mikiones**
fixes problem in my base when mining spots are to far from storage

### CODE REVIEW

**Comment by cyberblast** [comment]
miners will fallback to dropmining when container is full. 
containers are very expensive, I'd really advice to switch to links as fast as possible. 
And I really want to reduce creep numbers as much as possible. 
But I'll think about it a second time.

**Comment by mikiones** [comment]
yes and  i have 2 containers full of energy and miners dropping on floor.

**Comment by cyberblast** [comment]
how about bigger hauler? would that be sufficient?

**Comment by mikiones** [comment]
dunno there is so much one hauler can do. i mean need to visit all sources (energy miners, minerals,links). its not case that he is to small. it that he travel too slow. but he cant move faster , ergo more haulers are needed.

**Comment by cyberblast** [comment]
yes I understand, but if its larger, it will not need to come back that soon and has more time to visit all the other targets. In the end its only a matter of how much can be moved around, and thats the sum of all carry parts of all haulers. no matter how many they are.

**Pull request closed without merging**
