### PR TITLE
dismantle action

### PR DESCRIPTION
**Pull request by mikiones**
#26

### CODE REVIEW

**Comment by cyberblast** [comment]
There should be a target validation. Or the creeps will eventually eat your base ;)

**Comment by mikiones** [comment]
yes i do have it inside privateer if in target room do things..

**Comment by cyberblast** [comment]
Yes, but in 4 weeks nobody will remember that. Could you please also implement an isValidTarget or isAddableTarget check? To see if its within our room. 
Dismantle is interesting for different things and will also get its own flag color for use within owned rooms...

**Comment by cyberblast** [comment]
Implemented it requirig explicit flag instead of "in my room" check (to enable dismantling in owned rooms as well)

**Pull request closed without merging**
