### PR TITLE
miners build own containers and repire them

### PR DESCRIPTION
**Pull request by mikiones**

### CODE REVIEW

**Comment by cyberblast** [comment]
Yes that may be a workaround. But this can't be the solution. 
The miner is configured to harvest 1 source in exactly the time it takes until it restores. This is the optimal way. If the miner does other jobs as well, it can't do it's job efficiently. 
This is a worker & tower task...

**Comment by mikiones** [comment]
the mining and repairing is in same tick in same tick so it still harvest all energy from sources

**Comment by cyberblast** [comment]
I dont think so, as harvesting and repairing is within the same [action pipeline](http://support.screeps.com/hc/en-us/articles/203137792-Simultaneous-execution-of-creep-actions).

**Comment by mikiones** [comment]
oh i see

**Pull request closed without merging**
